from __future__ import annotations


def build_strategy_definitions(strategy_definition_cls):
    return (
        strategy_definition_cls("trend_pullback_long", "Trend Pullback", "trend", "LONG", "trend_pullback"),
        strategy_definition_cls("trend_pullback_short", "Trend Pullback", "trend", "SHORT", "trend_pullback"),
        strategy_definition_cls(
            "hma_ema_trend_long",
            "HMA/EMA Trend Long",
            "trend",
            "LONG",
            "hma_ema_trend",
            ui_label="HMA/EMA Trend Long",
        ),
        strategy_definition_cls(
            "hma_ema_trend_short",
            "HMA/EMA Trend Short",
            "trend",
            "SHORT",
            "hma_ema_trend",
            ui_label="HMA/EMA Trend Short",
        ),
        strategy_definition_cls("breakout_confirmation_long", "Breakout Confirmation", "breakout", "LONG", "breakout_confirmation"),
        strategy_definition_cls("breakout_confirmation_short", "Breakout Confirmation", "breakout", "SHORT", "breakout_confirmation"),
        strategy_definition_cls("squeeze_expansion_long", "Squeeze Expansion", "volatility", "LONG", "squeeze_expansion"),
        strategy_definition_cls("squeeze_expansion_short", "Squeeze Expansion", "volatility", "SHORT", "squeeze_expansion"),
        strategy_definition_cls("reversal_cluster_long", "Reversal Cluster", "reversal", "LONG", "reversal_cluster"),
        strategy_definition_cls("reversal_cluster_short", "Reversal Cluster", "reversal", "SHORT", "reversal_cluster"),
        strategy_definition_cls(
            "supertrend_psar_long",
            "SuperTrend + PSAR",
            "confirmation",
            "LONG",
            "supertrend_psar",
            ui_label="SuperTrend + PSAR Direction",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "supertrend_psar_short",
            "SuperTrend + PSAR",
            "confirmation",
            "SHORT",
            "supertrend_psar",
            ui_label="SuperTrend + PSAR Direction",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls("obv_divergence_long", "OBV Divergence", "divergence", "LONG", "obv_divergence"),
        strategy_definition_cls("obv_divergence_short", "OBV Divergence", "divergence", "SHORT", "obv_divergence"),
        strategy_definition_cls("keltner_pullback_long", "Keltner Pullback", "trend", "LONG", "keltner_pullback"),
        strategy_definition_cls("keltner_pullback_short", "Keltner Pullback", "trend", "SHORT", "keltner_pullback"),
        strategy_definition_cls("keltner_breakout_long", "Keltner Breakout", "breakout", "LONG", "keltner_breakout"),
        strategy_definition_cls("keltner_breakout_short", "Keltner Breakout", "breakout", "SHORT", "keltner_breakout"),
        strategy_definition_cls("keltner_mean_reversion_long", "Keltner Mean Reversion", "reversal", "LONG", "keltner_mean_reversion"),
        strategy_definition_cls("keltner_mean_reversion_short", "Keltner Mean Reversion", "reversal", "SHORT", "keltner_mean_reversion"),
        strategy_definition_cls("vwap_reclaim_long", "VWAP Reclaim", "trend", "LONG", "vwap_reclaim"),
        strategy_definition_cls("vwap_reclaim_short", "VWAP Reclaim", "trend", "SHORT", "vwap_reclaim"),
        strategy_definition_cls("morning_star_fib_long", "Morning Star + Fib", "reversal", "LONG", "morning_star_fib"),
        strategy_definition_cls("morning_star_fib_short", "Morning Star + Fib", "reversal", "SHORT", "morning_star_fib"),
        strategy_definition_cls(
            "fractal_breakout_long",
            "Fractal Breakout",
            "breakout",
            "LONG",
            "fractal_breakout",
            ui_label="Fractal Structure Breakout",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "fractal_breakout_short",
            "Fractal Breakout",
            "breakout",
            "SHORT",
            "fractal_breakout",
            ui_label="Fractal Structure Breakout",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "anchored_vwap_long",
            "Anchored VWAP",
            "trend",
            "LONG",
            "anchored_vwap",
            ui_label="Fixed VWAP 기반 롱 컨텍스트",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls(
            "anchored_vwap_short",
            "Anchored VWAP",
            "trend",
            "SHORT",
            "anchored_vwap",
            ui_label="Fixed VWAP 기반 숏 컨텍스트",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls("institutional_accumulation_long", "Institutional Accumulation", "accumulation", "LONG", "accumulation_pattern"),
        strategy_definition_cls("poc_rotation_long", "POC Rotation / VAH-VAL", "levels", "LONG", "poc_rotation"),
        strategy_definition_cls("poc_rotation_short", "POC Rotation / VAH-VAL", "levels", "SHORT", "poc_rotation"),
        strategy_definition_cls("ichimoku_breakout_long", "Ichimoku Breakout", "breakout", "LONG", "ichimoku_breakout"),
        strategy_definition_cls(
            "ichimoku_breakout_short",
            "Ichimoku Breakout",
            "breakout",
            "SHORT",
            "ichimoku_breakout",
            ui_label="Ichimoku Bearish Context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "fractal_alligator_long",
            "Fractal + Alligator",
            "trend",
            "LONG",
            "fractal_alligator",
            ui_label="Fractal/Trend Structure Context",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls(
            "fractal_alligator_short",
            "Fractal + Alligator",
            "trend",
            "SHORT",
            "fractal_alligator",
            ui_label="Fractal/Trend Structure Context",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls(
            "chaikin_flow_long",
            "Chaikin Flow",
            "flow",
            "LONG",
            "chaikin_flow",
            ui_label="Chaikin Money-Flow Context",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "chaikin_flow_short",
            "Chaikin Flow",
            "flow",
            "SHORT",
            "chaikin_flow",
            ui_label="Chaikin Money-Flow Context",
            presentation_type="context",
            implementation_level="partial",
        ),
    )
