from __future__ import annotations


def build_strategy_definitions(strategy_definition_cls):
    return (
        strategy_definition_cls("trend_pullback_long", "추세 지속 눌림목", "trend", "LONG", "trend_pullback"),
        strategy_definition_cls("trend_pullback_short", "추세 지속 눌림목", "trend", "SHORT", "trend_pullback"),
        strategy_definition_cls("breakout_confirmation_long", "돌파 확인형", "breakout", "LONG", "breakout_confirmation"),
        strategy_definition_cls("breakout_confirmation_short", "돌파 확인형", "breakout", "SHORT", "breakout_confirmation"),
        strategy_definition_cls("squeeze_expansion_long", "스퀴즈 발사형", "volatility", "LONG", "squeeze_expansion"),
        strategy_definition_cls("squeeze_expansion_short", "스퀴즈 발사형", "volatility", "SHORT", "squeeze_expansion"),
        strategy_definition_cls("reversal_cluster_long", "반전 클러스터", "reversal", "LONG", "reversal_cluster"),
        strategy_definition_cls("reversal_cluster_short", "반전 클러스터", "reversal", "SHORT", "reversal_cluster"),
        strategy_definition_cls(
            "supertrend_psar_long",
            "SuperTrend + PSAR 이중확인",
            "confirmation",
            "LONG",
            "supertrend_psar",
            ui_label="SuperTrend + PSAR 방향 정렬",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "supertrend_psar_short",
            "SuperTrend + PSAR 이중확인",
            "confirmation",
            "SHORT",
            "supertrend_psar",
            ui_label="SuperTrend + PSAR 방향 정렬",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls("obv_divergence_long", "OBV 다이버전스", "divergence", "LONG", "obv_divergence"),
        strategy_definition_cls("obv_divergence_short", "OBV 다이버전스", "divergence", "SHORT", "obv_divergence"),
        strategy_definition_cls("keltner_pullback_long", "Keltner Pullback", "trend", "LONG", "keltner_pullback"),
        strategy_definition_cls("keltner_pullback_short", "Keltner Pullback", "trend", "SHORT", "keltner_pullback"),
        strategy_definition_cls("keltner_breakout_long", "Keltner Breakout", "breakout", "LONG", "keltner_breakout"),
        strategy_definition_cls("keltner_breakout_short", "Keltner Breakout", "breakout", "SHORT", "keltner_breakout"),
        strategy_definition_cls("keltner_mean_reversion_long", "Keltner Mean Reversion", "reversal", "LONG", "keltner_mean_reversion"),
        strategy_definition_cls("keltner_mean_reversion_short", "Keltner Mean Reversion", "reversal", "SHORT", "keltner_mean_reversion"),
        strategy_definition_cls("vwap_reclaim_long", "VWAP 반등/거절형", "trend", "LONG", "vwap_reclaim"),
        strategy_definition_cls("vwap_reclaim_short", "VWAP 반등/거절형", "trend", "SHORT", "vwap_reclaim"),
        strategy_definition_cls("morning_star_fib_long", "Morning Star + Fib 골든존", "reversal", "LONG", "morning_star_fib"),
        strategy_definition_cls("morning_star_fib_short", "Morning Star + Fib 골든존", "reversal", "SHORT", "morning_star_fib"),
        strategy_definition_cls(
            "fractal_breakout_long",
            "Fractal Breakout",
            "breakout",
            "LONG",
            "fractal_breakout",
            ui_label="Fractal 구조 돌파 감시",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "fractal_breakout_short",
            "Fractal Breakout",
            "breakout",
            "SHORT",
            "fractal_breakout",
            ui_label="Fractal 구조 돌파 감시",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "anchored_vwap_long",
            "Anchored VWAP",
            "trend",
            "LONG",
            "anchored_vwap",
            ui_label="Fixed VWAP 기반 롱 컨텍스트",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls(
            "anchored_vwap_short",
            "Anchored VWAP",
            "trend",
            "SHORT",
            "anchored_vwap",
            ui_label="Fixed VWAP 기반 숏 컨텍스트",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls("institutional_accumulation_long", "기관 매집형", "accumulation", "LONG", "accumulation_pattern"),
        strategy_definition_cls("poc_rotation_long", "POC 리클레임 / VAH-VAL 회전", "levels", "LONG", "poc_rotation"),
        strategy_definition_cls("poc_rotation_short", "POC 리클레임 / VAH-VAL 회전", "levels", "SHORT", "poc_rotation"),
        strategy_definition_cls("ichimoku_breakout_long", "Ichimoku 돌파형", "breakout", "LONG", "ichimoku_breakout"),
        strategy_definition_cls(
            "ichimoku_breakout_short",
            "Ichimoku 돌파형",
            "breakout",
            "SHORT",
            "ichimoku_breakout",
            ui_label="Ichimoku 하향 이탈형",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "fractal_alligator_long",
            "Fractal + Alligator",
            "trend",
            "LONG",
            "fractal_alligator",
            ui_label="Fractal/추세 구조 감시",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls(
            "fractal_alligator_short",
            "Fractal + Alligator",
            "trend",
            "SHORT",
            "fractal_alligator",
            ui_label="Fractal/추세 구조 감시",
            presentation_type="context",
            implementation_level="proxy",
        ),
        strategy_definition_cls(
            "chaikin_flow_long",
            "Chaikin 독립 전략",
            "flow",
            "LONG",
            "chaikin_flow",
            ui_label="Chaikin 자금흐름 감시",
            presentation_type="context",
            implementation_level="partial",
        ),
        strategy_definition_cls(
            "chaikin_flow_short",
            "Chaikin 독립 전략",
            "flow",
            "SHORT",
            "chaikin_flow",
            ui_label="Chaikin 자금흐름 감시",
            presentation_type="context",
            implementation_level="partial",
        ),
    )
